#source 'https://mirrors.tuna.tsinghua.edu.cn/cocoapods/'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'VMProjectTool' do

  use_frameworks!

  
  pod 'ReactiveObjC'

  
end



